### ISSUE TITLE
You suck

### ISSUE THREAD

**Issue by GanyusLeftHorn** [timing1337/mineplex-reborn#3]
holy fuck i want to breed hu tao so bad. everytime i look at that face i want to rape her and plant my seed inside her pretty pussy. make her mine.

**Comment by nitrog0d** [comment]
oh my fucking god i want Saya to perform the fnaf 5 real ending on me. I so desperately want her to tear my organs out and make a little home inside. I need her to beat the actual ever-living fuck out of me. I need her to make me her drums. I want to rip off my skin in one fell swoop and line her drums with it. She will slowly and painfully gourge out my eyballs with her drumsticks. Should i seek help? Is there any hope for me at all left?

**Comment by timing1337** [comment]
kys
