### ISSUE TITLE
Please take this repository down immediately 

### ISSUE THREAD

**Issue by johnny-flynn** [timing1337/mineplex-reborn#8]
This code is the legal property of Mineplex and we kindly ask that it is removed immediately. If this request is not met immediately we will file a DMCA takedown.

**Comment by Nixuge** [comment]
Hi Johnny

**Comment by johnny-flynn** [comment]
Hi Nixuge

**Comment by Nixuge** [comment]
how r u

**Comment by johnny-flynn** [comment]
I am fine, how can I help you

**Comment by Nixuge** [comment]
Do u like skiing?
